Repository oktrifianto/grip-concept, pull requests merged in 2020-10, with the labels that each got.

#1 Add styles
  style.css
Labels: hacktoberfest-accepted

#3 Add javascript
  index.html
Labels: hacktoberfest-accepted

#4 Update main.js
  main.js
Labels: hacktoberfest-accepted

#5 Update style.css
  style.css
Labels: hacktoberfest-accepted

#6 Update style body
  style.css
Labels: enhancement, hacktoberfest-accepted

#7 Add Dockerfile to running under docker container
  Dockerfile
Labels: hacktoberfest-accepted, question

#8 add content4 and content5 with font family
  index.html
  style.css
Labels: hacktoberfest-accepted
